sudo: false
language: node_js
node_js:
  - 6
  - 8

env:
  global:
    - CXX=g++-4.9

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

cache: yarn
script: yarn test:travis
