sudo: false
language: node_js
node_js:
- "4"
- "5"
script: npm run travis
env:
  - CXX=g++-4.8
cache: apt
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
notifications:
  email: false
