#!/usr/bin/env perl

use strict;
use warnings;
use 5.010;

use App::Daemon qw(daemonize);
use File::Slurp qw(read_file write_file);
use LWP::UserAgent;

$App::Daemon::as_user = 'www-data';
$App::Daemon::logfile = '/tmp/dorfmap-bgdata.log';

daemonize();

our $VERSION = '0.01';

my $ua = LWP::UserAgent->new;
$ua->timeout(2);

my $re_pingdev = qr{
	(?: phone | printer | server | wifi )
	:
	(?<host> [^:\t\s]+ )
}x;

sub ping_host {
	my ($host) = @_;

	system( qw( ping -n -c 1 -W 1 ), $host);

	write_file("/srv/www/${host}.ping", ($? == 0) ? '1' : '0');

	return;
}

while (sleep(120)) {

	for my $line (read_file('coordinates')) {
		if ($line =~ $re_pingdev) {
			ping_host($+{host});
		}
	}

	$ua->get('http://door/status');
	if ($ua->is_success) {
		write_file('/srv/www/doorstatus', $ua->decoded_content);
	}
	else {
		write_file('/srv/www/doorstatus', -1);
	}

}

__END__

=head1 NAME

=head1 SYNOPSIS

=head1 VERSION

=head1 DESCRIPTION

=head1 OPTIONS

=over

=back

=head1 EXIT STATUS

=head1 CONFIGURATION

None.

=head1 DEPENDENCIES

=over

=back

=head1 BUGS AND LIMITATIONS

=head1 AUTHOR

Copyright (C) 2013 by Daniel Friesel E<lt>derf@finalrewind.orgE<gt>

=head1 LICENSE

  0. You just DO WHAT THE FUCK YOU WANT TO.
