global.io = require('socket.io-client');
global.Hammer = require('hammerjs');
global._ = require('underscore');
require('angular');
require('angular-socket-io');
require('angular-animate');
require('angular-aria');
require('angular-material');
require('angular-busy');
require('opentip');
